#! /usr/bin/python3
"""
This script parses SLURM output files generated by the convolution job script
"""

import sys
from argparse import ArgumentParser

DIR_DATA = "../../data/raw"

def main():
  args = parse_arguments(sys.argv[1:])

  with open(f'{DIR_DATA}/convolution.tsv', 'w') as output_tsv:
    output_tsv.write('GPU\tMeasurement\tDuration\n')

    for filename in args.filenames:
      filename = f'{DIR_DATA}/{filename}'
      
      with open(filename, 'r') as f:
        gpu_type = None

        for line in f.readlines():
          words = line.split()

          if len(words) > 1 and words[-2] == 'run':
            gpu_type = ' '.join(words[:-2])[:-1]
            print(gpu_type)

          if len(words) > 4 and words[-1] == 'seconds':
            duration = words[-2]
            measurement = words[-4][1:-2]
            print(measurement)
            print(duration)
            output_tsv.write(f'{gpu_type}\t{measurement}\t{duration}\n')

def parse_arguments(args):
  parser = ArgumentParser(description="Parse SLURM output for the convolution job scripts.")
  parser.add_argument('filenames', metavar='Filename', type=str, nargs='+', help='One or more filenames of output files generated by the job script')
  return parser.parse_args(args)

if __name__ == '__main__':
  main()
